# Generated by Django 4.0.1 on 2022-02-19 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internetshop', '0001_initial'),
        ('basketapp', '0002_alter_basket_product_alter_basket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
